[build]
  command = "npm run build"
  publish = "dist/registration-app/browser"

[[plugins]]
  package = "@netlify/angular-runtime"
  enabled = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
